
window.dataViews = {
    '':{}
    ,'Givers':{
        implementation:'simpleGateway'
        ,ServerDSN:'Givers'
        ,ServerSingleDSN:'aGiver'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:true,OnDeleteChangeStatus:'Status=Inaktiv',srcTable:'Giver'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'Fadderbarns':{
        implementation:'simpleGateway'
        ,ServerDSN:'Fadderbarns'
        ,ServerSingleDSN:'aFadderbarn'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,Sort:'Nbr'
        ,SortType:'undefined',allowListCache:true,OnDeleteChangeStatus:'Status=Inaktiv',srcTable:'Fadderbarn'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'Users':{
        implementation:'simpleGateway'
        ,ServerDSN:'Users'
        ,ServerSingleDSN:'aUser'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:true,srcTable:'User'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'Cassettes':{
        implementation:'simpleGateway'
        ,ServerDSN:'Cassettes'
        ,ServerSingleDSN:'aCassette'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:true,srcTable:'Cassette'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'Churchs':{
        implementation:'simpleGateway'
        ,ServerDSN:'Churchs'
        ,ServerSingleDSN:'aChurch'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:true,srcTable:'Church'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'Companys':{
        implementation:'simpleGateway'
        ,ServerDSN:'Companys'
        ,ServerSingleDSN:'aCompany'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:true,srcTable:'Company'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'Betels':{
        implementation:'simpleGateway'
        ,ServerDSN:'Betels'
        ,ServerSingleDSN:'aBetel'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:true,srcTable:'Betel'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'GivProjs':{
        implementation:'simpleGateway'
        ,ServerDSN:'GivProjs'
        ,ServerSingleDSN:'aGivProj'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:true,srcTable:'GivProj'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'Projects':{
        implementation:'simpleGateway'
        ,ServerDSN:'Projects'
        ,ServerSingleDSN:'aProject'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:true,srcTable:'Project'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'SidaProjs':{
        implementation:'simpleGateway'
        ,ServerDSN:'SidaProjs'
        ,ServerSingleDSN:'aSidaProj'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:true,srcTable:'SidaProj'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'Payments':{
        implementation:'simpleGateway'
        ,ServerDSN:'Payments'
        ,ServerSingleDSN:'aPayment'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,Sort:'Date'
        ,SortType:'DESC',allowListCache:true,srcTable:'Payment'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'Payment_LastIns':{
        implementation:'simpleGateway'
        ,ServerDSN:'Payment_LastIns'
        ,ServerSingleDSN:'aPayment_LastIn'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:false
        ,pageSize:1,Sort:'Date'
        ,SortType:'DESC',allowListCache:false,srcTable:'Payment'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'Payment_LastOuts':{
        implementation:'simpleGateway'
        ,ServerDSN:'Payment_LastOuts'
        ,ServerSingleDSN:'aPayment_LastOut'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:false
        ,pageSize:1,Sort:'Date'
        ,SortType:'DESC',allowListCache:false,srcTable:'Payment'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'Payment_Sums':{
        implementation:'simpleGateway'
        ,ServerDSN:'Payment_Sums'
        ,ServerSingleDSN:'aPayment_Sum'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,Sort:'Date'
        ,SortType:'DESC',allowListCache:true,srcTable:'Payment'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'GiverProjects':{
        implementation:'simpleGateway'
        ,ServerDSN:'GiverProjects'
        ,ServerSingleDSN:'aGiverProject'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,pageSize:25,Sort:'GivProj.ProjectId'
        ,SortType:'ASC',allowListCache:true,srcTable:'GivProj'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'OCRImports':{
        implementation:'simpleGateway'
        ,ServerDSN:'OCRImports'
        ,ServerSingleDSN:'aOCRImport'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,Sort:'date'
        ,SortType:'DESC',allowListCache:true,srcTable:'OCRImport'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'GiverFadderbarns':{
        implementation:'simpleGateway'
        ,ServerDSN:'GiverFadderbarns'
        ,ServerSingleDSN:'aGiverFadderbarn'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,Sort:'Nbr'
        ,SortType:'undefined',allowListCache:true,srcTable:'Fadderbarn'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'GiverPayments':{
        implementation:'simpleGateway'
        ,ServerDSN:'GiverPayments'
        ,ServerSingleDSN:'aGiverPayment'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,pageSize:10,Sort:'Payment.Date'
        ,SortType:'DESC',allowListCache:true,srcTable:'Payment'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'Contacts':{
        implementation:'simpleGateway'
        ,ServerDSN:'Contacts'
        ,ServerSingleDSN:'aContact'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:true,srcTable:'Contact'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'SocialWorkers':{
        implementation:'simpleGateway'
        ,ServerDSN:'SocialWorkers'
        ,ServerSingleDSN:'aSocialWorker'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:true,srcTable:'SocialWorker'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'Databases':{
        implementation:'simpleGateway'
        ,ServerDSN:'Databases'
        ,ServerSingleDSN:'aDatabase'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,Sort:''
        ,SortType:'undefined',allowListCache:true,allowListAllCache:true,allwaysDisplayAll:true,srcTable:'Database'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'CustomReports':{
        implementation:'simpleGateway'
        ,ServerDSN:'CustomReports'
        ,ServerSingleDSN:'aCustomReport'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,Sort:'Name'
        ,SortType:'ASC',allowListCache:true,srcTable:'CustomReport'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'Caravans':{
        implementation:'simpleGateway'
        ,ServerDSN:'Caravans'
        ,ServerSingleDSN:'aCaravan'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,Sort:'Nr'
        ,SortType:'ASC',allowListCache:true,srcTable:'Caravan'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'Evangelists':{
        implementation:'simpleGateway'
        ,ServerDSN:'Evangelists'
        ,ServerSingleDSN:'aEvangelist'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:true,srcTable:'Evangelist'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'GiverEvangelists':{
        implementation:'simpleGateway'
        ,ServerDSN:'GiverEvangelists'
        ,ServerSingleDSN:'aGiverEvangelist'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:false,srcTable:'Evangelist'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'SocialWorkerFadderbarns':{
        implementation:'simpleGateway'
        ,ServerDSN:'SocialWorkerFadderbarns'
        ,ServerSingleDSN:'aSocialWorkerFadderbarn'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:true,srcTable:'Fadderbarn'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'GiverCaravans':{
        implementation:'simpleGateway'
        ,ServerDSN:'GiverCaravans'
        ,ServerSingleDSN:'aGiverCaravan'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:true,srcTable:'Caravan'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'GiverSelects':{
        implementation:'simpleGateway'
        ,ServerDSN:'GiverSelects'
        ,ServerSingleDSN:'aGiverSelect'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:true,srcTable:'Giver'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'SocialWorkerSelects':{
        implementation:'simpleGateway'
        ,ServerDSN:'SocialWorkerSelects'
        ,ServerSingleDSN:'aSocialWorkerSelect'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:true,srcTable:'SocialWorker'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'PaymentInLists':{
        implementation:'simpleGateway'
        ,ServerDSN:'PaymentInLists'
        ,ServerSingleDSN:'aPaymentInList'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,pageSize:5000,Sort:'Payment.Id'
        ,SortType:'DESC',allowListCache:false,srcTable:'Payment'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'PaymentOuts':{
        implementation:'simpleGateway'
        ,ServerDSN:'PaymentOuts'
        ,ServerSingleDSN:'aPaymentOut'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:true,srcTable:'Payment'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'Actions':{
        implementation:'simpleGateway'
        ,ServerDSN:'Actions'
        ,ServerSingleDSN:'aAction'
        ,PK:'id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:true,srcTable:'action'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'FadderbarnActions':{
        implementation:'simpleGateway'
        ,ServerDSN:'FadderbarnActions'
        ,ServerSingleDSN:'aFadderbarnAction'
        ,PK:'id'
        ,getAsPages:true
        ,getCount:true
        ,Sort:'action.date'
        ,SortType:'DESC',allowListCache:true,srcTable:'action'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'ProjectGivers':{
        implementation:'simpleGateway'
        ,ServerDSN:'ProjectGivers'
        ,ServerSingleDSN:'aProjectGiver'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,pageSize:25,allowListCache:true,srcTable:'GivProj'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'FadderbarnGivers':{
        implementation:'simpleGateway'
        ,ServerDSN:'FadderbarnGivers'
        ,ServerSingleDSN:'aFadderbarnGiver'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:true,srcTable:'Giver'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'SocialWorkAreas':{
        implementation:'simpleGateway'
        ,ServerDSN:'SocialWorkAreas'
        ,ServerSingleDSN:'aSocialWorkArea'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:true,srcTable:'SocialWorkArea'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'SocialWorkerAreas':{
        implementation:'simpleGateway'
        ,ServerDSN:'SocialWorkerAreas'
        ,ServerSingleDSN:'aSocialWorkerArea'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:true,srcTable:'SocialWorkArea'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'EvangelistActions':{
        implementation:'simpleGateway'
        ,ServerDSN:'EvangelistActions'
        ,ServerSingleDSN:'aEvangelistAction'
        ,PK:'id'
        ,getAsPages:true
        ,getCount:true
        ,Sort:'Date'
        ,SortType:'DESC',allowListCache:true,srcTable:'action'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'EvangelistGivers':{
        implementation:'simpleGateway'
        ,ServerDSN:'EvangelistGivers'
        ,ServerSingleDSN:'aEvangelistGiver'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:true,srcTable:'Giver'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'Areas':{
        implementation:'simpleGateway'
        ,ServerDSN:'Areas'
        ,ServerSingleDSN:'aArea'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,allowListCache:true,srcTable:'SocialWorkArea'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }
,'GivProjPromisess':{
        implementation:'simpleGateway'
        ,ServerDSN:'GivProjPromisess'
        ,ServerSingleDSN:'aGivProjPromises'
        ,PK:'Id'
        ,getAsPages:true
        ,getCount:true
        ,pageSize:10,Sort:'StartDt'
        ,SortType:'DESC',allowListCache:true,srcTable:'GivProj'
        ,curRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        },allRecordSet:{
            start:0
            ,curPage:0
            ,Hits:0
            ,HighestHit:0
            ,Count:undefined	
            ,isDirty:true
            ,Rows:[]
        }
    }

}
