function(ns) {
	var out = new Array();
	var o=out
	try {
out.push("<span class=\"CaravansBigIcon BigIcon TaskEdit4\" task=\"Project4.Task\" component=\"protoHeader613\">Husvagn</span> \n\n<span class=\"EditIcons\">    <span class=\"ListIcon EditIcon\">\n        <a href=\"Pages/Caravans\" class=\"ajaxLink\">Lista</a>\n    </span>\n</span><script>\n    document.title = $('<div/>').html(\"Husvagn s&ouml;k\").text();\n</script><br/>\n<table class=\"EditTable\" id=\"CaravanTab");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\">\n<tr><th colspan=\"5\">Uppgifter</th></tr>\n<tr><td>Nummer</td><td><input id=\"search_Nr618");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=3 value=\"");
out.push(dataViews.Caravans.getFilter('Nr','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td>M&auml;rke</td><td><input id=\"search_Make518");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=11 value=\"");
out.push(dataViews.Caravans.getFilter('Make','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td rowspan=\"7\" valign=\"top\">Utrustning:<br/><text");
try{d='area';}catch(e){d=''}out.push(d);
 out.push(" wrap=\"On\" cols=\"56\" rows=\"6\" id=\"search_Equipment525");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" tabindex=18>");
out.push(dataViews.Caravans.getFilter('Equipment','*'));
 out.push("</text");
try{d='area';}catch(e){d=''}out.push(d);
 out.push("></td></tr>\n<tr><td>RegNr</td><td><input id=\"search_Regnr514");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=4 value=\"");
out.push(dataViews.Caravans.getFilter('Regnr','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td>&Aring;rsmodel</td><td><input id=\"search_Year616");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=12 value=\"");
out.push(dataViews.Caravans.getFilter('Year','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td></tr>\n<tr><td>&Auml;gareNamn:</td><td><input id=\"search_OwnerName519");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=5 value=\"");
out.push(dataViews.Caravans.getFilter('OwnerName','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td>&Auml;garePostNr:</td><td><input id=\"search_OwnerPostCode521");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=13 value=\"");
out.push(dataViews.Caravans.getFilter('OwnerPostCode','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td></tr>\n<tr><td>&Auml;gareAdres:</td><td><input id=\"search_OwnerAddress520");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=6 value=\"");
out.push(dataViews.Caravans.getFilter('OwnerAddress','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td>&Auml;garePost:</td><td><input id=\"search_OwnerPostTown522");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=14 value=\"");
out.push(dataViews.Caravans.getFilter('OwnerPostTown','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td></tr>\n<tr><td>Tel</td><td><input id=\"search_Tel523");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=7 value=\"");
out.push(dataViews.Caravans.getFilter('Tel','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td>Placering:</td><td><input id=\"search_Location526");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=15 value=\"");
out.push(dataViews.Caravans.getFilter('Location','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td></tr>\n<tr><td>Pris:</td><td><input id=\"search_Price524");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=8 value=\"");
out.push(dataViews.Caravans.getFilter('Price','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td>Bekr&auml;ftSki</td><td><input id=\"search_ConfirmDate529");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=16 value=\"");
out.push(dataViews.Caravans.getFilter('ConfirmDate','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td></tr>\n<tr><td>Totalpris:</td><td><input id=\"search_TotalPrice617");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=9 value=\"");
out.push(dataViews.Caravans.getFilter('TotalPrice','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td>UthyrdTill:</td><td><input id=\"search_HiredBy527");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=17 value=\"");
out.push(dataViews.Caravans.getFilter('HiredBy','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td></tr>\n<tr><td><a class=\"ajaxLink\" href=\"Pages/Giver/");
try{d=r.GivNr;}catch(e){d=''}out.push(d);
 out.push("\">Giv.nr</a>:</td><td><input id=\"search_GivNr528");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=10 value=\"");
out.push(dataViews.Caravans.getFilter('GivNr','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td>#</td><td><input id=\"search_Id513");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Caravans.getFilter('Id','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td></td></tr>\n</table>\n<center>\n<button class=\"CancelBut\" id=\"clear");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" onclick=\"\ndataViews.Caravans.clearFilter();\n\n                jQuery('#search_Id513");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Regnr514");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Notes515");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Status516");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Db517");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Make518");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_OwnerName519");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_OwnerAddress520");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_OwnerPostCode521");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_OwnerPostTown522");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Tel523");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Price524");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Equipment525");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Location526");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_HiredBy527");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_GivNr528");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_ConfirmDate529");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Year616");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_TotalPrice617");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Nr618");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n//App3.Navigate2('local/Pages/Caravan/'+id,{target:'AppPages'});\n\">Rensa</button>\n|\n<input class=\"SearchBut\" type=\"button\" id=\"doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" tabindex=19 value=\"Sök\"\n onclick=\"\ndataViews.Caravans.clearFilter();\nvar elm;\n             dataViews.Caravans.addFilter('Id','$',jQuery('#search_Id513");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Caravans.addFilter('Regnr','*',jQuery('#search_Regnr514");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Caravans.addFilter('Notes','*',jQuery('#search_Notes515");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Caravans.addFilter('Status','*',jQuery('#search_Status516");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Caravans.addFilter('Db','*',jQuery('#search_Db517");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Caravans.addFilter('Make','*',jQuery('#search_Make518");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Caravans.addFilter('OwnerName','*',jQuery('#search_OwnerName519");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Caravans.addFilter('OwnerAddress','*',jQuery('#search_OwnerAddress520");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Caravans.addFilter('OwnerPostCode','*',jQuery('#search_OwnerPostCode521");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Caravans.addFilter('OwnerPostTown','*',jQuery('#search_OwnerPostTown522");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Caravans.addFilter('Tel','*',jQuery('#search_Tel523");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Caravans.addFilter('Price','*',jQuery('#search_Price524");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Caravans.addFilter('Equipment','*',jQuery('#search_Equipment525");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Caravans.addFilter('Location','*',jQuery('#search_Location526");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Caravans.addFilter('HiredBy','*',jQuery('#search_HiredBy527");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Caravans.addFilter('GivNr','*',jQuery('#search_GivNr528");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Caravans.addFilter('ConfirmDate','*',jQuery('#search_ConfirmDate529");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Caravans.addFilter('Year','*',jQuery('#search_Year616");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Caravans.addFilter('TotalPrice','*',jQuery('#search_TotalPrice617");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Caravans.addFilter('Nr','*',jQuery('#search_Nr618");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \ndataViews.Caravans.firstRow({OnComplete:function() {\n    if (dataViews.Caravans.curRecordSet.Hits > 0) {\n        var id = dataViews.Caravans.curRecordSet.Rows[0]['Id'];\n        App3.Navigate2('local/Pages/Caravan/'+id,{target:'AppPages'});\n    } else {\n        alert('Ingen träff');\n     }\n},NoNewPage:function() {\n        alert('Ingen träff');\n     }});\n\"/></center>\n\n\n\n");

	return out.join('');
	}catch(e){
		console.error(e);
		return 'Template Error:'+e.message;
	}
}
