function(ns) {
	var out = new Array();
	var o=out
	try {
out.push("<span class=\"CompanysBigIcon BigIcon TaskEdit4\" task=\"Project4.Task\" component=\"protoHeader599\">F&ouml;retag</span> \n\n<span class=\"EditIcons\">    <span class=\"ListIcon EditIcon\">\n        <a href=\"Pages/Companys\" class=\"ajaxLink\">Lista</a>\n    </span>\n</span><br/>\n<table class=\"EditTable\">\n<thead><tr><th colspan=\"7\">Givare</th></tr></thead>\n<tr>\n<td style=\"text-align:right\">Namn:</td><td><input id=\"search_CompanyName587");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Companys.getFilter('CompanyName','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td>\n<td style=\"text-align:right\">Nr:</td><td><input id=\"search_Id586");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Companys.getFilter('Id','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td>\n<td rowspan=\"6\"><text");
try{d='area';}catch(e){d=''}out.push(d);
 out.push(" wrap=\"off\" cols=\"30\" rows=\"6\" id=\"search_Notes595");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\">");
out.push(dataViews.Companys.getFilter('Notes','*'));
 out.push("</text");
try{d='area';}catch(e){d=''}out.push(d);
 out.push("></td>\n</tr>\n<tr>\n<td style=\"text-align:right\">Adress:</td><td><input id=\"search_Address588");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Companys.getFilter('Address','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td>\n<td style=\"text-align:right\">Telefon:</td><td><input id=\"search_Tel591");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Companys.getFilter('Tel','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td>\n</tr>\n<tr>\n<td style=\"text-align:right\">PostNr:</td><td><input id=\"search_Zip589");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Companys.getFilter('Zip','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td>\n<td style=\"text-align:right\">BankGiro:</td><td><input id=\"search_BankGiro592");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Companys.getFilter('BankGiro','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td>\n</tr>\n<tr>\n<td style=\"text-align:right\">PostOrt:</td><td><input id=\"search_ZipTown590");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Companys.getFilter('ZipTown','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td>\n<td style=\"text-align:right\">PosttGiro:</td><td><input id=\"search_PostGiro593");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Companys.getFilter('PostGiro','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td>\n</tr>\n<tr>\n<td style=\"text-align:right\">Epost:</td><td>??</td>\n<td style=\"text-align:right\">kod:</td><td><input id=\"search_Code594");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Companys.getFilter('Code','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td>\n</tr>\n</table>\n<center>\n<button onclick=\"\ndataViews.Companys.clearFilter();\nApp3.Navigate2('local/Pages/Company/'+id,{target:'AppPages'});\n\">Rensa</button>\n|\n<input type=\"button\" id=\"doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" value=\"Sök\"\n onclick=\"\ndataViews.Companys.clearFilter();\nvar elm;\n             dataViews.Companys.addFilter('Id','*',jQuery('#search_Id586");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Companys.addFilter('CompanyName','*',jQuery('#search_CompanyName587");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Companys.addFilter('Address','*',jQuery('#search_Address588");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Companys.addFilter('Zip','*',jQuery('#search_Zip589");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Companys.addFilter('ZipTown','*',jQuery('#search_ZipTown590");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Companys.addFilter('Tel','*',jQuery('#search_Tel591");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Companys.addFilter('BankGiro','*',jQuery('#search_BankGiro592");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Companys.addFilter('PostGiro','*',jQuery('#search_PostGiro593");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Companys.addFilter('Code','*',jQuery('#search_Code594");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Companys.addFilter('Notes','*',jQuery('#search_Notes595");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Companys.addFilter('Status','*',jQuery('#search_Status596");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \ndataViews.Companys.firstRow({OnComplete:function() {\n    if (dataViews.Companys.curRecordSet.Hits > 0) {\n        var id = dataViews.Companys.curRecordSet.Rows[0]['Id'];\n        App3.Navigate2('local/Pages/Company/'+id,{target:'AppPages'});\n    } else {\n        alert('Ingen träff');\n     }\n},NoNewPage:function() {\n        alert('Ingen träff');\n     }});\n\"/></center>\n\n\n");

	return out.join('');
	}catch(e){
		console.error(e);
		return 'Template Error:'+e.message;
	}
}
