function(ns) {
	var out = new Array();
	var o=out
	try {
out.push("<span class=\"EvangelistGiversBigIcon BigIcon TaskEdit4\" task=\"Project4.Task\" component=\"EvangelistGivers_ProtoHeader\">EvangelistGiver</span> \n\n<span class=\"EditIcons\"><span class=\"NewIcon EditIcon\">\n        <a href=\"Pages/EvangelistGiverNew\" class=\"ajaxLink\">Ny</a>\n    </span>\n    <span class=\"ListIcon EditIcon\">\n        <a href=\"Pages/EvangelistGivers\" class=\"ajaxLink\">Lista</a>\n    </span>\n</span><br/>\n\n");

if ((ns.data)&&(!ns['forceRead'])) {
 out.push("\n\n<span class=\"EditIcons\"><span class=\"TaskEdit4\" Task=\"Project4.Task\" Component=\"EvangelistGiverList_fields\"> </span>\n");

if (ns.Recordset) {
if (ns.Recordset.Hits ==0) {
out.push('<i>0 Poster');
} else {
out.push('<i>Post '+(ns.Recordset.start+1)+' till '+(ns.Recordset.Hits+ns.Recordset.start));
}
if (ns.Recordset.Count) {
if ((ns.DataView)&&(ns.DataView.filterActive==true)) {
//display filtered count..
out.push(' av '+ns.Recordset.filteredCount);
} else {
out.push(' av '+ns.Recordset.Count);
}
}
out.push('</i>');
}

 out.push("\n<a title=\"Ta bort filter\" onclick=\"$j('#Prog");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').addClass('ajaxLoading');dataViews.EvangelistGivers.clearFilter();dataViews.EvangelistGivers.firstPage({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView});$j('#Prog");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').removeClass('ajaxLoading');},NoNewPage:function(){$j('#Prog");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').removeClass('ajaxLoading');}});\"><span class=\"RecordsetClearFilterIcon EditIcon\">&nb");
try{d='sp';}catch(e){d=''}out.push(d);
 out.push(";</span></a>\n<a title=\"F&ouml;rsta\" onclick=\"$j('#Prog");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').addClass('ajaxLoading');dataViews.EvangelistGivers.firstPage({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView});$j('#Prog");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').removeClass('ajaxLoading');},NoNewPage:function(){$j('#Prog");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').removeClass('ajaxLoading');}});\"><span class=\"RecordsetFirstIcon EditIcon\">&nb");
try{d='sp';}catch(e){d=''}out.push(d);
 out.push(";</span></a>\n<a title=\"F&ouml;reg&aring;nde\" onclick=\"$j('#Prog");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').addClass('ajaxLoading');dataViews.EvangelistGivers.previousPage({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView});$j('#Prog");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').removeClass('ajaxLoading');},NoNewPage:function(){$j('#Prog");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').removeClass('ajaxLoading');}});\"><span class=\"RecordsetPreviousIcon EditIcon\">&nb");
try{d='sp';}catch(e){d=''}out.push(d);
 out.push(";</span></a>\n<a title=\"N&auml;sta\" onclick=\"$j('#Prog");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').addClass('ajaxLoading');dataViews.EvangelistGivers.nextPage({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView});$j('#Prog");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').removeClass('ajaxLoading');},NoNewPage:function(){$j('#Prog");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').removeClass('ajaxLoading');}});\"><span class=\"RecordsetNextIcon EditIcon\">&nb");
try{d='sp';}catch(e){d=''}out.push(d);
 out.push(";</span></a>\n<a title=\"Sista\" onclick=\"$j('#Prog");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').addClass('ajaxLoading');dataViews.EvangelistGivers.lastPage({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView});$j('#Prog");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').removeClass('ajaxLoading');},NoNewPage:function(){$j('#Prog");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').removeClass('ajaxLoading');}});\"><span class=\"RecordsetLastIcon EditIcon\">&nb");
try{d='sp';}catch(e){d=''}out.push(d);
 out.push(";</span></a>\n<a title=\"H&auml;mta alla\" onclick=\"$j('#Prog");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').addClass('ajaxLoading');dataViews.EvangelistGivers.getAllRows({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView});$j('#Prog");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').removeClass('ajaxLoading');},NoNewPage:function(){$j('#Prog");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').removeClass('ajaxLoading');}});\"><span class=\"RecordsetAllIcon EditIcon\">&nb");
try{d='sp';}catch(e){d=''}out.push(d);
 out.push(";</span></a>\n<input type=\"button\" style=\"display:none\" id=\"Filter_");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" onclick=\"\ndataViews.EvangelistGivers.clearFilter();\n\ndataViews.EvangelistGivers.addFilter('Id','*',document.getElementById('Filter_EvangelistGiver_Id_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value);\ndataViews.EvangelistGivers.addFilter('Name','*',document.getElementById('Filter_EvangelistGiver_Name_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value);\ndataViews.EvangelistGivers.addFilter('Address','*',document.getElementById('Filter_EvangelistGiver_Address_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value);\ndataViews.EvangelistGivers.addFilter('ZipCode','*',document.getElementById('Filter_EvangelistGiver_ZipCode_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value);\ndataViews.EvangelistGivers.addFilter('ZipTown','*',document.getElementById('Filter_EvangelistGiver_ZipTown_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value);\ndataViews.EvangelistGivers.addFilter('Nr','*',document.getElementById('Filter_EvangelistGiver_Nr_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value);\ndataViews.EvangelistGivers.addFilter('Land','*',document.getElementById('Filter_EvangelistGiver_Land_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value);\ndataViews.EvangelistGivers.addFilter('Tel','*',document.getElementById('Filter_EvangelistGiver_Tel_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value);\ndataViews.EvangelistGivers.addFilter('Mob','*',document.getElementById('Filter_EvangelistGiver_Mob_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value);\ndataViews.EvangelistGivers.addFilter('Email','*',document.getElementById('Filter_EvangelistGiver_Email_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value);\ndataViews.EvangelistGivers.addFilter('Paper','*',document.getElementById('Filter_EvangelistGiver_Paper_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value);\ndataViews.EvangelistGivers.addFilter('Member','*',document.getElementById('Filter_EvangelistGiver_Member_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value);\ndataViews.EvangelistGivers.addFilter('StartD','*',document.getElementById('Filter_EvangelistGiver_StartD_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value);\ndataViews.EvangelistGivers.addFilter('ProjCode','*',document.getElementById('Filter_EvangelistGiver_ProjCode_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value);\ndataViews.EvangelistGivers.addFilter('Status','*',document.getElementById('Filter_EvangelistGiver_Status_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value);\ndataViews.EvangelistGivers.addFilter('CoAddress','*',document.getElementById('Filter_EvangelistGiver_CoAddress_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value);\ndataViews.EvangelistGivers.addFilter('LastName','*',document.getElementById('Filter_EvangelistGiver_LastName_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value);\ndataViews.EvangelistGivers.addFilter('PersonNbr','*',document.getElementById('Filter_EvangelistGiver_PersonNbr_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value);\ndataViews.EvangelistGivers.addFilter('Letter','*',document.getElementById('Filter_EvangelistGiver_Letter_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value);\ndataViews.EvangelistGivers.addFilter('Tags','*',document.getElementById('Filter_EvangelistGiver_Tags_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value);\ndataViews.EvangelistGivers.addFilter('Db','*',document.getElementById('Filter_EvangelistGiver_Db_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value);\n\ndataViews.EvangelistGivers.getList({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{navTarget:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView });}});\n\"/>\n<span id=\"Prog");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\"></span>\n</span>\n\n<table class=\"ListTable\" ><tr>\n\n<th width=\"\" class=\"Col_EvangelistGiver_Id_List\"><a class=\"SortColumn\" onclick=\"\ndataViews.EvangelistGivers.setSort('Id');\ndataViews.EvangelistGivers.getList({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{navTarget:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView });}});\"><u>Id</u></a><span class=\"TaskEdit4\" Task=\"Project4.Task\" Component=\"EvangelistGiver_Id_List\"> </span></th>\n\n<th width=\"\" class=\"Col_EvangelistGiver_Name_List\"><a class=\"SortColumn\" onclick=\"\ndataViews.EvangelistGivers.setSort('Name');\ndataViews.EvangelistGivers.getList({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{navTarget:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView });}});\"><u>Name</u></a><span class=\"TaskEdit4\" Task=\"Project4.Task\" Component=\"EvangelistGiver_Name_List\"> </span></th>\n\n<th width=\"\" class=\"Col_EvangelistGiver_Address_List\"><a class=\"SortColumn\" onclick=\"\ndataViews.EvangelistGivers.setSort('Address');\ndataViews.EvangelistGivers.getList({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{navTarget:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView });}});\"><u>Address</u></a><span class=\"TaskEdit4\" Task=\"Project4.Task\" Component=\"EvangelistGiver_Address_List\"> </span></th>\n\n<th width=\"\" class=\"Col_EvangelistGiver_ZipCode_List\"><a class=\"SortColumn\" onclick=\"\ndataViews.EvangelistGivers.setSort('ZipCode');\ndataViews.EvangelistGivers.getList({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{navTarget:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView });}});\"><u>ZipCode</u></a><span class=\"TaskEdit4\" Task=\"Project4.Task\" Component=\"EvangelistGiver_ZipCode_List\"> </span></th>\n\n<th width=\"\" class=\"Col_EvangelistGiver_ZipTown_List\"><a class=\"SortColumn\" onclick=\"\ndataViews.EvangelistGivers.setSort('ZipTown');\ndataViews.EvangelistGivers.getList({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{navTarget:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView });}});\"><u>ZipTown</u></a><span class=\"TaskEdit4\" Task=\"Project4.Task\" Component=\"EvangelistGiver_ZipTown_List\"> </span></th>\n\n<th width=\"\" class=\"Col_EvangelistGiver_Nr_List\"><a class=\"SortColumn\" onclick=\"\ndataViews.EvangelistGivers.setSort('Nr');\ndataViews.EvangelistGivers.getList({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{navTarget:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView });}});\"><u>Nr</u></a><span class=\"TaskEdit4\" Task=\"Project4.Task\" Component=\"EvangelistGiver_Nr_List\"> </span></th>\n\n<th width=\"\" class=\"Col_EvangelistGiver_Land_List\"><a class=\"SortColumn\" onclick=\"\ndataViews.EvangelistGivers.setSort('Land');\ndataViews.EvangelistGivers.getList({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{navTarget:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView });}});\"><u>Land</u></a><span class=\"TaskEdit4\" Task=\"Project4.Task\" Component=\"EvangelistGiver_Land_List\"> </span></th>\n\n<th width=\"\" class=\"Col_EvangelistGiver_Tel_List\"><a class=\"SortColumn\" onclick=\"\ndataViews.EvangelistGivers.setSort('Tel');\ndataViews.EvangelistGivers.getList({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{navTarget:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView });}});\"><u>Tel</u></a><span class=\"TaskEdit4\" Task=\"Project4.Task\" Component=\"EvangelistGiver_Tel_List\"> </span></th>\n\n<th width=\"\" class=\"Col_EvangelistGiver_Mob_List\"><a class=\"SortColumn\" onclick=\"\ndataViews.EvangelistGivers.setSort('Mob');\ndataViews.EvangelistGivers.getList({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{navTarget:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView });}});\"><u>Mob</u></a><span class=\"TaskEdit4\" Task=\"Project4.Task\" Component=\"EvangelistGiver_Mob_List\"> </span></th>\n\n<th width=\"\" class=\"Col_EvangelistGiver_Email_List\"><a class=\"SortColumn\" onclick=\"\ndataViews.EvangelistGivers.setSort('Email');\ndataViews.EvangelistGivers.getList({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{navTarget:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView });}});\"><u>Email</u></a><span class=\"TaskEdit4\" Task=\"Project4.Task\" Component=\"EvangelistGiver_Email_List\"> </span></th>\n\n<th width=\"\" class=\"Col_EvangelistGiver_Paper_List\"><a class=\"SortColumn\" onclick=\"\ndataViews.EvangelistGivers.setSort('Paper');\ndataViews.EvangelistGivers.getList({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{navTarget:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView });}});\"><u>Paper</u></a><span class=\"TaskEdit4\" Task=\"Project4.Task\" Component=\"EvangelistGiver_Paper_List\"> </span></th>\n\n<th width=\"\" class=\"Col_EvangelistGiver_Member_List\"><a class=\"SortColumn\" onclick=\"\ndataViews.EvangelistGivers.setSort('Member');\ndataViews.EvangelistGivers.getList({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{navTarget:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView });}});\"><u>Member</u></a><span class=\"TaskEdit4\" Task=\"Project4.Task\" Component=\"EvangelistGiver_Member_List\"> </span></th>\n\n<th width=\"\" class=\"Col_EvangelistGiver_StartD_List\"><a class=\"SortColumn\" onclick=\"\ndataViews.EvangelistGivers.setSort('StartD');\ndataViews.EvangelistGivers.getList({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{navTarget:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView });}});\"><u>StartD</u></a><span class=\"TaskEdit4\" Task=\"Project4.Task\" Component=\"EvangelistGiver_StartD_List\"> </span></th>\n\n<th width=\"\" class=\"Col_EvangelistGiver_ProjCode_List\"><a class=\"SortColumn\" onclick=\"\ndataViews.EvangelistGivers.setSort('ProjCode');\ndataViews.EvangelistGivers.getList({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{navTarget:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView });}});\"><u>ProjCode</u></a><span class=\"TaskEdit4\" Task=\"Project4.Task\" Component=\"EvangelistGiver_ProjCode_List\"> </span></th>\n\n<th width=\"\" class=\"Col_EvangelistGiver_Status_List\"><a class=\"SortColumn\" onclick=\"\ndataViews.EvangelistGivers.setSort('Status');\ndataViews.EvangelistGivers.getList({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{navTarget:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView });}});\"><u>Status</u></a><span class=\"TaskEdit4\" Task=\"Project4.Task\" Component=\"EvangelistGiver_Status_List\"> </span></th>\n\n<th width=\"\" class=\"Col_EvangelistGiver_CoAddress_List\"><a class=\"SortColumn\" onclick=\"\ndataViews.EvangelistGivers.setSort('CoAddress');\ndataViews.EvangelistGivers.getList({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{navTarget:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView });}});\"><u>CoAddress</u></a><span class=\"TaskEdit4\" Task=\"Project4.Task\" Component=\"EvangelistGiver_CoAddress_List\"> </span></th>\n\n<th width=\"\" class=\"Col_EvangelistGiver_LastName_List\"><a class=\"SortColumn\" onclick=\"\ndataViews.EvangelistGivers.setSort('LastName');\ndataViews.EvangelistGivers.getList({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{navTarget:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView });}});\"><u>LastName</u></a><span class=\"TaskEdit4\" Task=\"Project4.Task\" Component=\"EvangelistGiver_LastName_List\"> </span></th>\n\n<th width=\"\" class=\"Col_EvangelistGiver_PersonNbr_List\"><a class=\"SortColumn\" onclick=\"\ndataViews.EvangelistGivers.setSort('PersonNbr');\ndataViews.EvangelistGivers.getList({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{navTarget:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView });}});\"><u>PersonNbr</u></a><span class=\"TaskEdit4\" Task=\"Project4.Task\" Component=\"EvangelistGiver_PersonNbr_List\"> </span></th>\n\n<th width=\"\" class=\"Col_EvangelistGiver_Letter_List\"><a class=\"SortColumn\" onclick=\"\ndataViews.EvangelistGivers.setSort('Letter');\ndataViews.EvangelistGivers.getList({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{navTarget:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView });}});\"><u>Letter</u></a><span class=\"TaskEdit4\" Task=\"Project4.Task\" Component=\"EvangelistGiver_Letter_List\"> </span></th>\n\n<th width=\"\" class=\"Col_EvangelistGiver_Tags_List\"><a class=\"SortColumn\" onclick=\"\ndataViews.EvangelistGivers.setSort('Tags');\ndataViews.EvangelistGivers.getList({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{navTarget:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView });}});\"><u>Tags</u></a><span class=\"TaskEdit4\" Task=\"Project4.Task\" Component=\"EvangelistGiver_Tags_List\"> </span></th>\n\n<th width=\"\" class=\"Col_EvangelistGiver_Db_List\"><a class=\"SortColumn\" onclick=\"\ndataViews.EvangelistGivers.setSort('Db');\ndataViews.EvangelistGivers.getList({OnComplete:function(data,Recordset,DataView){App3.Navigate2('");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("',{navTarget:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView });}});\"><u>Db</u></a><span class=\"TaskEdit4\" Task=\"Project4.Task\" Component=\"EvangelistGiver_Db_List\"> </span></th>\n\n</tr><tr>\n\n<td><input id=\"Filter_EvangelistGiver_Id_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" style=\"width:95%\" value=\"");
out.push(dataViews.EvangelistGivers.getFilter('Id','*'));
 out.push("\" onkeypress=\"var e = (event) ? event : window.event;char=(e.charCode)?e.charCode:e.keyCode;if(char==13){$j('#Filter_");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click();}\"/></td>\n\n<td><input id=\"Filter_EvangelistGiver_Name_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" style=\"width:95%\" value=\"");
out.push(dataViews.EvangelistGivers.getFilter('Name','*'));
 out.push("\" onkeypress=\"var e = (event) ? event : window.event;char=(e.charCode)?e.charCode:e.keyCode;if(char==13){$j('#Filter_");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click();}\"/></td>\n\n<td><input id=\"Filter_EvangelistGiver_Address_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" style=\"width:95%\" value=\"");
out.push(dataViews.EvangelistGivers.getFilter('Address','*'));
 out.push("\" onkeypress=\"var e = (event) ? event : window.event;char=(e.charCode)?e.charCode:e.keyCode;if(char==13){$j('#Filter_");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click();}\"/></td>\n\n<td><input id=\"Filter_EvangelistGiver_ZipCode_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" style=\"width:95%\" value=\"");
out.push(dataViews.EvangelistGivers.getFilter('ZipCode','*'));
 out.push("\" onkeypress=\"var e = (event) ? event : window.event;char=(e.charCode)?e.charCode:e.keyCode;if(char==13){$j('#Filter_");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click();}\"/></td>\n\n<td><input id=\"Filter_EvangelistGiver_ZipTown_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" style=\"width:95%\" value=\"");
out.push(dataViews.EvangelistGivers.getFilter('ZipTown','*'));
 out.push("\" onkeypress=\"var e = (event) ? event : window.event;char=(e.charCode)?e.charCode:e.keyCode;if(char==13){$j('#Filter_");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click();}\"/></td>\n\n<td><input id=\"Filter_EvangelistGiver_Nr_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" style=\"width:95%\" value=\"");
out.push(dataViews.EvangelistGivers.getFilter('Nr','*'));
 out.push("\" onkeypress=\"var e = (event) ? event : window.event;char=(e.charCode)?e.charCode:e.keyCode;if(char==13){$j('#Filter_");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click();}\"/></td>\n\n<td><input id=\"Filter_EvangelistGiver_Land_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" style=\"width:95%\" value=\"");
out.push(dataViews.EvangelistGivers.getFilter('Land','*'));
 out.push("\" onkeypress=\"var e = (event) ? event : window.event;char=(e.charCode)?e.charCode:e.keyCode;if(char==13){$j('#Filter_");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click();}\"/></td>\n\n<td><input id=\"Filter_EvangelistGiver_Tel_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" style=\"width:95%\" value=\"");
out.push(dataViews.EvangelistGivers.getFilter('Tel','*'));
 out.push("\" onkeypress=\"var e = (event) ? event : window.event;char=(e.charCode)?e.charCode:e.keyCode;if(char==13){$j('#Filter_");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click();}\"/></td>\n\n<td><input id=\"Filter_EvangelistGiver_Mob_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" style=\"width:95%\" value=\"");
out.push(dataViews.EvangelistGivers.getFilter('Mob','*'));
 out.push("\" onkeypress=\"var e = (event) ? event : window.event;char=(e.charCode)?e.charCode:e.keyCode;if(char==13){$j('#Filter_");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click();}\"/></td>\n\n<td><input id=\"Filter_EvangelistGiver_Email_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" style=\"width:95%\" value=\"");
out.push(dataViews.EvangelistGivers.getFilter('Email','*'));
 out.push("\" onkeypress=\"var e = (event) ? event : window.event;char=(e.charCode)?e.charCode:e.keyCode;if(char==13){$j('#Filter_");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click();}\"/></td>\n\n<td><input id=\"Filter_EvangelistGiver_Paper_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" style=\"width:95%\" value=\"");
out.push(dataViews.EvangelistGivers.getFilter('Paper','*'));
 out.push("\" onkeypress=\"var e = (event) ? event : window.event;char=(e.charCode)?e.charCode:e.keyCode;if(char==13){$j('#Filter_");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click();}\"/></td>\n\n<td><input id=\"Filter_EvangelistGiver_Member_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" style=\"width:95%\" value=\"");
out.push(dataViews.EvangelistGivers.getFilter('Member','*'));
 out.push("\" onkeypress=\"var e = (event) ? event : window.event;char=(e.charCode)?e.charCode:e.keyCode;if(char==13){$j('#Filter_");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click();}\"/></td>\n\n<td><input id=\"Filter_EvangelistGiver_StartD_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" style=\"width:95%\" value=\"");
out.push(dataViews.EvangelistGivers.getFilter('StartD','*'));
 out.push("\" onkeypress=\"var e = (event) ? event : window.event;char=(e.charCode)?e.charCode:e.keyCode;if(char==13){$j('#Filter_");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click();}\"/></td>\n\n<td><input id=\"Filter_EvangelistGiver_ProjCode_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" style=\"width:95%\" value=\"");
out.push(dataViews.EvangelistGivers.getFilter('ProjCode','*'));
 out.push("\" onkeypress=\"var e = (event) ? event : window.event;char=(e.charCode)?e.charCode:e.keyCode;if(char==13){$j('#Filter_");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click();}\"/></td>\n\n<td><input id=\"Filter_EvangelistGiver_Status_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" style=\"width:95%\" value=\"");
out.push(dataViews.EvangelistGivers.getFilter('Status','*'));
 out.push("\" onkeypress=\"var e = (event) ? event : window.event;char=(e.charCode)?e.charCode:e.keyCode;if(char==13){$j('#Filter_");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click();}\"/></td>\n\n<td><input id=\"Filter_EvangelistGiver_CoAddress_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" style=\"width:95%\" value=\"");
out.push(dataViews.EvangelistGivers.getFilter('CoAddress','*'));
 out.push("\" onkeypress=\"var e = (event) ? event : window.event;char=(e.charCode)?e.charCode:e.keyCode;if(char==13){$j('#Filter_");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click();}\"/></td>\n\n<td><input id=\"Filter_EvangelistGiver_LastName_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" style=\"width:95%\" value=\"");
out.push(dataViews.EvangelistGivers.getFilter('LastName','*'));
 out.push("\" onkeypress=\"var e = (event) ? event : window.event;char=(e.charCode)?e.charCode:e.keyCode;if(char==13){$j('#Filter_");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click();}\"/></td>\n\n<td><input id=\"Filter_EvangelistGiver_PersonNbr_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" style=\"width:95%\" value=\"");
out.push(dataViews.EvangelistGivers.getFilter('PersonNbr','*'));
 out.push("\" onkeypress=\"var e = (event) ? event : window.event;char=(e.charCode)?e.charCode:e.keyCode;if(char==13){$j('#Filter_");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click();}\"/></td>\n\n<td><input id=\"Filter_EvangelistGiver_Letter_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" style=\"width:95%\" value=\"");
out.push(dataViews.EvangelistGivers.getFilter('Letter','*'));
 out.push("\" onkeypress=\"var e = (event) ? event : window.event;char=(e.charCode)?e.charCode:e.keyCode;if(char==13){$j('#Filter_");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click();}\"/></td>\n\n<td><input id=\"Filter_EvangelistGiver_Tags_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" style=\"width:95%\" value=\"");
out.push(dataViews.EvangelistGivers.getFilter('Tags','*'));
 out.push("\" onkeypress=\"var e = (event) ? event : window.event;char=(e.charCode)?e.charCode:e.keyCode;if(char==13){$j('#Filter_");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click();}\"/></td>\n\n<td><input id=\"Filter_EvangelistGiver_Db_List");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" style=\"width:95%\" value=\"");
out.push(dataViews.EvangelistGivers.getFilter('Db','*'));
 out.push("\" onkeypress=\"var e = (event) ? event : window.event;char=(e.charCode)?e.charCode:e.keyCode;if(char==13){$j('#Filter_");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click();}\"/></td>\n\n</tr>\n");

var r;

for(var ri=0;ri<ns.data.length;ri++) {
r = ns.data[ri];


 out.push("\n<tr >\n\n<td ><a class=ajaxLink href=Pages/EvangelistGiver/");
try{d=r.Id;}catch(e){d=''}out.push(d);
 out.push(">");
try{d=r.Id;}catch(e){d=''}out.push(d);
 out.push("</a></td>\n\n<td >");
try{d=r['Name'];}catch(e){d=''}out.push(d);
 out.push("</td>\n\n<td >");
try{d=r['Address'];}catch(e){d=''}out.push(d);
 out.push("</td>\n\n<td >");
try{d=r['ZipCode'];}catch(e){d=''}out.push(d);
 out.push("</td>\n\n<td >");
try{d=r['ZipTown'];}catch(e){d=''}out.push(d);
 out.push("</td>\n\n<td >");
try{d=r['Nr'];}catch(e){d=''}out.push(d);
 out.push("</td>\n\n<td >");
try{d=r['Land'];}catch(e){d=''}out.push(d);
 out.push("</td>\n\n<td >");
try{d=r['Tel'];}catch(e){d=''}out.push(d);
 out.push("</td>\n\n<td >");
try{d=r['Mob'];}catch(e){d=''}out.push(d);
 out.push("</td>\n\n<td >");
try{d=r['Email'];}catch(e){d=''}out.push(d);
 out.push("</td>\n\n<td >");
try{d=r['Paper'];}catch(e){d=''}out.push(d);
 out.push("</td>\n\n<td >");
try{d=r['Member'];}catch(e){d=''}out.push(d);
 out.push("</td>\n\n<td >");
try{d=r['StartD'];}catch(e){d=''}out.push(d);
 out.push("</td>\n\n<td >");
try{d=r['ProjCode'];}catch(e){d=''}out.push(d);
 out.push("</td>\n\n<td >");
try{d=r['Status'];}catch(e){d=''}out.push(d);
 out.push("</td>\n\n<td >");
try{d=r['CoAddress'];}catch(e){d=''}out.push(d);
 out.push("</td>\n\n<td >");
try{d=r['LastName'];}catch(e){d=''}out.push(d);
 out.push("</td>\n\n<td >");
try{d=r['PersonNbr'];}catch(e){d=''}out.push(d);
 out.push("</td>\n\n<td >");
try{d=r['Letter'];}catch(e){d=''}out.push(d);
 out.push("</td>\n\n<td >");
try{d=r['Tags'];}catch(e){d=''}out.push(d);
 out.push("</td>\n\n<td >");
try{d=r['Db'];}catch(e){d=''}out.push(d);
 out.push("</td>\n\n</tr>\n");
}
if (ns.data.length == 0) {//no rows code.
 out.push("\n<tr><td colspan=\"22\"><center>Ingen</center></td></tr>\n");
 } 
 out.push("\n\n</table>\n");
} else {
//no data retrieved yet... load it..

 out.push("<script>\ndataViews.EvangelistGivers.getList({OnComplete:function(data,Recordset,DataView){App3.Navigate2(\"");
try{d=ns._fullurl;}catch(e){d=''}out.push(d);
 out.push("\",{navTarget:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',data:data,Recordset:Recordset,DataView:DataView });}});\n\n</script><img src=\"img/ajaxLoading.gif\"/>ladda...\n");
}
 out.push("\n\n");

	return out.join('');
	}catch(e){
		console.error(e);
		return 'Template Error:'+e.message;
	}
}
