function(ns) {
	var out = new Array();
	var o=out
	try {
out.push("<span class=\"EvangelistsBigIcon BigIcon TaskEdit4\" task=\"Project4.Task\" component=\"protoHeader394\">Evangelist</span> \n\n<span class=\"EditIcons\">    <span class=\"ListIcon EditIcon\">\n        <a href=\"Pages/Evangelists\" class=\"ajaxLink\">Lista</a>\n    </span>\n</span><script>\n    document.title = $('<div/>').html(\"Evangelist s&ouml;k\").text();\n</script><br/>\n<table class=\"EditTable\" id=\"EvangelistEditTab");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\">\n<tr><th colspan=\"5\">Uppgifter</th></tr>\n<tr><td>Nummer</td><td><input id=\"search_Id396");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=3 value=\"");
out.push(dataViews.Evangelists.getFilter('Id','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td></td><td></td><td rowspan=\"6\" valign=\"top\">Noteringar:<br/><text");
try{d='area';}catch(e){d=''}out.push(d);
 out.push(" wrap=\"On\" cols=\"40\" rows=\"8\" id=\"search_Notes406");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" tabindex=15>");
out.push(dataViews.Evangelists.getFilter('Notes','*'));
 out.push("</text");
try{d='area';}catch(e){d=''}out.push(d);
 out.push("></td></tr>\n<tr><td>Namn</td><td colspan=\"2\"><input id=\"search_Name397");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=4 value=\"");
out.push(dataViews.Evangelists.getFilter('Name','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td></td></tr>\n<tr><td>Omr&aring;de#:</td><td><input id=\"search_Area1402");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=6 value=\"");
out.push(dataViews.Evangelists.getFilter('Area1','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td>Omr&aring;de:</td><td><input id=\"search_Area403");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=5 value=\"");
out.push(dataViews.Evangelists.getFilter('Area','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td></tr>\n<tr><td>Landskod:</td><td><input id=\"search_CountryCode405");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=7 value=\"");
out.push(dataViews.Evangelists.getFilter('CountryCode','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td>F&ouml;dd:</td><td><input id=\"search_DOB398");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=8 value=\"");
out.push(dataViews.Evangelists.getFilter('DOB','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td></tr>\n<tr><td>Giv.nr:</td><td><input id=\"search_GiverId399");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=9 value=\"");
out.push(dataViews.Evangelists.getFilter('GiverId','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td>Inkom:</td><td><input id=\"search_TGdt404");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=10 value=\"");
out.push(dataViews.Evangelists.getFilter('TGdt','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td></tr>\n<tr><td>Kr/M&aring;n:</td><td><input id=\"search_Mkr401");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=11 value=\"");
out.push(dataViews.Evangelists.getFilter('Mkr','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td>Reg:</td><td><input id=\"search_RegDate648");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=12 value=\"");
out.push(dataViews.Evangelists.getFilter('RegDate','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td></tr>\n<tr><td>Projekt:</td><td><input id=\"search_ProjectId446");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=13 value=\"");
out.push(dataViews.Evangelists.getFilter('ProjectId','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td>B&ouml;rjat:</td><td><input id=\"search_HelpD400");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=14 value=\"");
out.push(dataViews.Evangelists.getFilter('HelpD','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td></td></tr>\n<tr><td>Tags:</td><td><input id=\"search_Tags697");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Evangelists.getFilter('Tags','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td></td><td></td><td></td></tr>\n</table>\n<center>\n<button class=\"CancelBut\" id=\"clear");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" onclick=\"\ndataViews.Evangelists.clearFilter();\n\n                jQuery('#search_Id396");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Name397");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_DOB398");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_GiverId399");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_HelpD400");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Mkr401");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Area1402");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Area403");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_TGdt404");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_CountryCode405");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Notes406");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_ProjectId446");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_RegDate648");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Tags697");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n//App3.Navigate2('local/Pages/Evangelist/'+id,{target:'AppPages'});\n\">Rensa</button>\n|\n<input class=\"SearchBut\" type=\"button\" id=\"doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" tabindex=16 value=\"Sök\"\n onclick=\"\ndataViews.Evangelists.clearFilter();\nvar elm;\n             dataViews.Evangelists.addFilter('Id','$',jQuery('#search_Id396");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Evangelists.addFilter('Name','*',jQuery('#search_Name397");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Evangelists.addFilter('DOB','*',jQuery('#search_DOB398");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Evangelists.addFilter('GiverId','*',jQuery('#search_GiverId399");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Evangelists.addFilter('HelpD','*',jQuery('#search_HelpD400");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Evangelists.addFilter('Mkr','*',jQuery('#search_Mkr401");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Evangelists.addFilter('Area1','*',jQuery('#search_Area1402");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Evangelists.addFilter('Area','*',jQuery('#search_Area403");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Evangelists.addFilter('TGdt','*',jQuery('#search_TGdt404");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Evangelists.addFilter('CountryCode','*',jQuery('#search_CountryCode405");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Evangelists.addFilter('Notes','*',jQuery('#search_Notes406");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Evangelists.addFilter('ProjectId','*',jQuery('#search_ProjectId446");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Evangelists.addFilter('RegDate','*',jQuery('#search_RegDate648");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n            \ndataViews.Evangelists.addFilter('Tags','£',jQuery('#search_Tags697");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \ndataViews.Evangelists.firstRow({OnComplete:function() {\n    if (dataViews.Evangelists.curRecordSet.Hits > 0) {\n        var id = dataViews.Evangelists.curRecordSet.Rows[0]['Id'];\n        App3.Navigate2('local/Pages/Evangelist/'+id,{target:'AppPages'});\n    } else {\n        alert('Ingen träff');\n     }\n},NoNewPage:function() {\n        alert('Ingen träff');\n     }});\n\"/></center>\n\n\n\n");

	return out.join('');
	}catch(e){
		console.error(e);
		return 'Template Error:'+e.message;
	}
}
