function(ns) {
	var out = new Array();
	var o=out
	try {
out.push("<span class=\"FadderbarnsBigIcon BigIcon TaskEdit4\" task=\"Project4.Task\" component=\"protoHeader217\">Fadderbarn</span> \n\n<span class=\"EditIcons\">    <span class=\"ListIcon EditIcon\">\n        <a href=\"Pages/Fadderbarns\" class=\"ajaxLink\">Lista</a>\n    </span>\n</span><script>\n    document.title = $('<div/>').html(\"Fadderbarn s&ouml;k\").text();\n</script><br/>\n<table class=\"EditTable\">\n<tr><th colspan=\"5\">Uppgifter</th></tr>\n<tr><td>Barnnr</td><td><input id=\"search_Nbr883");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Fadderbarns.getFilter('Nbr','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td>Id:</td><td><input id=\"search_Id219");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" size=4 class=exactSearch  tabindex=3 value=\"");
out.push(dataViews.Fadderbarns.getFilter('Id','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td rowspan=\"5\" valign=\"top\">Noteringar:<br/><text");
try{d='area';}catch(e){d=''}out.push(d);
 out.push(" wrap=\"off\" cols=\"54\" rows=\"4\" id=\"search_Notes232");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" tabindex=19>");
out.push(dataViews.Fadderbarns.getFilter('Notes','*'));
 out.push("</text");
try{d='area';}catch(e){d=''}out.push(d);
 out.push("></td></tr>\n<tr><td>Namn</td><td colspan=\"3\"><input id=\"search_Name221");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" size=34 tabindex=4 value=\"");
out.push(dataViews.Fadderbarns.getFilter('Name','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td></tr>\n<tr><td>Omr&aring;de#:</td><td><input id=\"search_Area1228");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" size=4 tabindex=5 value=\"");
out.push(dataViews.Fadderbarns.getFilter('Area1','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td>Omr&aring;de:</td><td><input id=\"search_Area229");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=6 value=\"");
out.push(dataViews.Fadderbarns.getFilter('Area','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td></tr>\n<tr><td>Landskod:</td><td><input id=\"search_CountryCode231");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" size=4 tabindex=7 value=\"");
out.push(dataViews.Fadderbarns.getFilter('CountryCode','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td>F&ouml;dd:</td><td><input id=\"search_DOB224");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" size=8 tabindex=8 value=\"");
out.push(dataViews.Fadderbarns.getFilter('DOB','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td></tr>\n<tr><td>Giv.nr:</td><td><input id=\"search_GiverId241");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" size=5 tabindex=9 value=\"");
out.push(dataViews.Fadderbarns.getFilter('GiverId','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td>Reg:</td><td><input id=\"search_RegDate368");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" size=8 tabindex=10 value=\"");
out.push(dataViews.Fadderbarns.getFilter('RegDate','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td></tr>\n<tr><td>Projekt</td><td><input id=\"search_ProjectId370");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" size=5 tabindex=11 value=\"");
out.push(dataViews.Fadderbarns.getFilter('ProjectId','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td>B&ouml;rjat:</td><td><input id=\"search_HelpD226");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" size=8 tabindex=12 value=\"");
out.push(dataViews.Fadderbarns.getFilter('HelpD','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td rowspan=\"5\">Egna Noteringar:<br/><text");
try{d='area';}catch(e){d=''}out.push(d);
 out.push(" wrap=\"off\" cols=\"54\" rows=\"4\" id=\"search_EgenNot235");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" tabindex=20>");
out.push(dataViews.Fadderbarns.getFilter('EgenNot','*'));
 out.push("</text");
try{d='area';}catch(e){d=''}out.push(d);
 out.push("></td></tr>\n<tr><td>Kr/M&aring;n:</td><td><input id=\"search_Mkr227");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" size=5 tabindex=13 value=\"");
out.push(dataViews.Fadderbarns.getFilter('Mkr','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td>Inkom:</td><td><input id=\"search_TGdt230");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" size=8 tabindex=14 value=\"");
out.push(dataViews.Fadderbarns.getFilter('TGdt','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td></tr>\n<tr><td>Faderns namn:</td><td><input id=\"search_FathersName222");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" size=5 tabindex=15 value=\"");
out.push(dataViews.Fadderbarns.getFilter('FathersName','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td>Social:</td><td><input id=\"search_Helper236");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=16 value=\"");
out.push(dataViews.Fadderbarns.getFilter('Helper','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td></tr>\n<tr><td>Moderns namn:</td><td><input id=\"search_MothersName223");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" size=5 tabindex=17 value=\"");
out.push(dataViews.Fadderbarns.getFilter('MothersName','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td>Guardian:</td><td><input id=\"search_Guardian243");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" tabindex=18 value=\"");
out.push(dataViews.Fadderbarns.getFilter('Guardian','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td></tr>\n<tr><td>Tags:</td><td><input id=\"search_Tags695");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Fadderbarns.getFilter('Tags','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td><td></td><td></td>\n</table>\n<center>\n<button class=\"CancelBut\" id=\"clear");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" onclick=\"\ndataViews.Fadderbarns.clearFilter();\n\n                jQuery('#search_Id219");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_ChildNr220");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Name221");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_FathersName222");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_MothersName223");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_DOB224");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_GiverId225");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_HelpD226");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Mkr227");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Area1228");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Area229");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_TGdt230");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_CountryCode231");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Notes232");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_EgenNot235");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Helper236");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_GiverId241");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Guardian243");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_RegDate368");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_ProjectId370");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Tags695");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_Nbr883");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n//App3.Navigate2('local/Pages/Fadderbarn/'+id,{target:'AppPages'});\n\">Rensa</button>\n|\n<input class=\"SearchBut\" type=\"button\" id=\"doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" tabindex=21 value=\"Sök\"\n onclick=\"\ndataViews.Fadderbarns.clearFilter();\nvar elm;\n             dataViews.Fadderbarns.addFilter('Id','$',jQuery('#search_Id219");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Fadderbarns.addFilter('ChildNr','*',jQuery('#search_ChildNr220");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Fadderbarns.addFilter('Name','*',jQuery('#search_Name221");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Fadderbarns.addFilter('FathersName','*',jQuery('#search_FathersName222");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Fadderbarns.addFilter('MothersName','*',jQuery('#search_MothersName223");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Fadderbarns.addFilter('DOB','*',jQuery('#search_DOB224");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Fadderbarns.addFilter('GiverId','*',jQuery('#search_GiverId225");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Fadderbarns.addFilter('HelpD','*',jQuery('#search_HelpD226");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Fadderbarns.addFilter('Mkr','*',jQuery('#search_Mkr227");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Fadderbarns.addFilter('Area1','*',jQuery('#search_Area1228");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Fadderbarns.addFilter('Area','*',jQuery('#search_Area229");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Fadderbarns.addFilter('TGdt','*',jQuery('#search_TGdt230");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Fadderbarns.addFilter('CountryCode','*',jQuery('#search_CountryCode231");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Fadderbarns.addFilter('Notes','*',jQuery('#search_Notes232");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Fadderbarns.addFilter('EgenNot','*',jQuery('#search_EgenNot235");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Fadderbarns.addFilter('Helper','*',jQuery('#search_Helper236");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Fadderbarns.addFilter('GiverId','*',jQuery('#search_GiverId241");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Fadderbarns.addFilter('Guardian','*',jQuery('#search_Guardian243");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Fadderbarns.addFilter('RegDate','*',jQuery('#search_RegDate368");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Fadderbarns.addFilter('ProjectId','*',jQuery('#search_ProjectId370");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n            \ndataViews.Fadderbarns.addFilter('Tags','£',jQuery('#search_Tags695");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Fadderbarns.addFilter('Nbr','$',jQuery('#search_Nbr883");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \ndataViews.Fadderbarns.firstRow({OnComplete:function() {\n    if (dataViews.Fadderbarns.curRecordSet.Hits > 0) {\n        var id = dataViews.Fadderbarns.curRecordSet.Rows[0]['Id'];\n        App3.Navigate2('local/Pages/Fadderbarn/'+id,{target:'AppPages'});\n    } else {\n        alert('Ingen träff');\n     }\n},NoNewPage:function() {\n        alert('Ingen träff');\n     }});\n\"/></center>\n\n\n<script>$('#search_Nbr883");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').select().focus();</script>\n");

	return out.join('');
	}catch(e){
		console.error(e);
		return 'Template Error:'+e.message;
	}
}
