function(ns) {
	var out = new Array();
	var o=out
	try {
out.push("<span class=\"PaymentsBigIcon BigIcon TaskEdit4\" task=\"Project4.Task\" component=\"protoHeader319\">Betalningar</span> \n\n<span class=\"EditIcons\"><span class=\"NewIcon EditIcon\">\n        <a href=\"Pages/PaymentNew\" class=\"ajaxLink\">Ny</a>\n    </span>\n    <span class=\"ListIcon EditIcon\">\n        <a href=\"Pages/Payments\" class=\"ajaxLink\">Lista</a>\n    </span>\n</span><br/>\n<table class=\"EditTable\" id=\"PaymentTab");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\">\n<thead><tr><th colspan=\"7\">Betalningar</th></tr></thead>\n<tr>\n<td style=\"text-align:right\">Datum:</td><td><input id=\"search_Date322");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Payments.getFilter('Date','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td>\n<td style=\"text-align:right\">Givare:</td><td><input id=\"search_GiverId323");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Payments.getFilter('GiverId','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td>\n<td style=\"text-align:right\">Projekt/Barn #</td><td><input id=\"search_ProjectId324");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Payments.getFilter('ProjectId','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td>\n</tr>\n\n<tr>\n<td style=\"text-align:right\">InKr:</td><td><input id=\"search_InKr326");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Payments.getFilter('InKr','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td>\n<td style=\"text-align:right\">OutKr:</td><td><input id=\"search_OutKr327");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Payments.getFilter('OutKr','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td>\n<td style=\"text-align:right\">Projekt/Barn</td><td><input id=\"search_PaymentType328");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Payments.getFilter('PaymentType','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td>\n</tr>\n\n<tr>\n<td style=\"text-align:right\">AdminKr:</td><td><input id=\"search_AdminCharge332");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Payments.getFilter('AdminCharge','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td>\n<td style=\"text-align:right\">Admin%:</td><td><input id=\"search_AdminPercent333");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Payments.getFilter('AdminPercent','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td>\n<td style=\"text-align:right\"></td><td></td>\n</tr>\n<tr>\n<td style=\"text-align:right\">Src:</td><td><input id=\"search_PaymentSource330");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Payments.getFilter('PaymentSource','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td>\n<td style=\"text-align:right\">SrcId:</td><td><input id=\"search_PaymentSourceId331");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Payments.getFilter('PaymentSourceId','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td>\n<td style=\"text-align:right\"></td><td></td>\n</tr>\n<tr>\n<td style=\"text-align:right\">Anv&auml;ndareNamn:</td><td><input id=\"search_AddedBy325");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Payments.getFilter('AddedBy','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td>\n<td style=\"text-align:right\">Anv&auml;ndare#:</td><td><input id=\"search_AddedByUserId329");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"");
out.push(dataViews.Payments.getFilter('AddedByUserId','*'));
 out.push("\" onkeydown=\"if (event.keyCode == 13) document.getElementById('doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').click()\"/></td>\n<td style=\"text-align:right\"></td><td></td>\n</tr>\n</table>\n<center>\n<button class=\"CancelBut\" id=\"clear");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" onclick=\"\ndataViews.Payments.clearFilter();\n\n                jQuery('#search_Date322");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_GiverId323");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_ProjectId324");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_AddedBy325");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_InKr326");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_OutKr327");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_PaymentType328");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_AddedByUserId329");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_PaymentSource330");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_PaymentSourceId331");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_AdminCharge332");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n                jQuery('#search_AdminPercent333");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val('');\n            \n//App3.Navigate2('local/Pages/Payment/'+id,{target:'AppPages'});\n\">Rensa</button>\n|\n<input class=\"SearchBut\" type=\"button\" id=\"doSearch");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\"  value=\"Sök\"\n onclick=\"\ndataViews.Payments.clearFilter();\nvar elm;\n             dataViews.Payments.addFilter('Date','*',jQuery('#search_Date322");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Payments.addFilter('GiverId','*',jQuery('#search_GiverId323");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Payments.addFilter('ProjectId','*',jQuery('#search_ProjectId324");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Payments.addFilter('AddedBy','*',jQuery('#search_AddedBy325");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Payments.addFilter('InKr','*',jQuery('#search_InKr326");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Payments.addFilter('OutKr','*',jQuery('#search_OutKr327");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Payments.addFilter('PaymentType','*',jQuery('#search_PaymentType328");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Payments.addFilter('AddedByUserId','*',jQuery('#search_AddedByUserId329");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Payments.addFilter('PaymentSource','*',jQuery('#search_PaymentSource330");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Payments.addFilter('PaymentSourceId','*',jQuery('#search_PaymentSourceId331");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Payments.addFilter('AdminCharge','*',jQuery('#search_AdminCharge332");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \n             dataViews.Payments.addFilter('AdminPercent','*',jQuery('#search_AdminPercent333");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').val());\n            \ndataViews.Payments.firstRow({OnComplete:function() {\n    if (dataViews.Payments.curRecordSet.Hits > 0) {\n        var id = dataViews.Payments.curRecordSet.Rows[0]['Id'];\n        App3.Navigate2('local/Pages/Payment/'+id,{target:'AppPages'});\n    } else {\n        alert('Ingen träff');\n     }\n},NoNewPage:function() {\n        alert('Ingen träff');\n     }});\n\"/></center>\n\n\n\n");

	return out.join('');
	}catch(e){
		console.error(e);
		return 'Template Error:'+e.message;
	}
}
