function(ns) {
	var out = new Array();
	var o=out
	try {
out.push("<span class=\"ProjectGiversBigIcon BigIcon TaskEdit4\" task=\"Project4.Task\" component=\"ProjectGiverNew_ProtoHeader\">ProjectGiver</span> \n\n<span class=\"EditIcons\"><span class=\"NewIcon EditIcon\">\n        <a href=\"Pages/ProjectGiverNew\" class=\"ajaxLink\">Ny</a>\n    </span>\n    <span class=\"ListIcon EditIcon\">\n        <a href=\"Pages/ProjectGivers\" class=\"ajaxLink\">Lista</a>\n    </span>\n</span><br/>\n\n\n<table class=\"EditTable\" >\n<thead>\n    <tr><th colspan='2'><center><span class=\"TaskEdit4\" task=\"Project4.Task\" component=\"ProjectGiverNew_fields\">Uppgifter</span></center></th></tr>\n</thead>\n<tbody>\n\n<tr><td><label>GiverId</label>:</td><td>\n<input type=\"text\" id=\"ProjectGiver_GiverId_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" value=\"0\" OnChange=\"\"/>\n<a style=\"cursor:pointer;\" onclick=\"\nif($j('#ProjectGiver_GiverId_NewPopUp");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("_area').css('display')=='none') {\n$j('#ProjectGiver_GiverId_NewPopUp");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("_area').show();\nApp3.Navigate2('local/Pages/GiverSelect',{target:'ProjectGiver_GiverId_NewPopUp");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("'});\n} else {\n$j('#ProjectGiver_GiverId_NewPopUp");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("_area').hide();\n}\n\"><span class=\"EditLink\" style=\"display:none;\" id=\"ProjectGiver_GiverId_NewPopUp");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("_display\">undefined</span>\n\n<button>Välj</button></a>\n<br/>\n<div id=\"ProjectGiver_GiverId_NewPopUp");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("_area\" style=\"display:none;position:relative;\" datadisplay=\"ProjectGiver_GiverId_NewPopUp");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("_display\" datastoreid=\"ProjectGiver_GiverId_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\"><div id=\"ProjectGiver_GiverId_NewPopUp");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" class=\"PopupSelect\" style=\"position:absolute;background:#EEEEEE;\">loading...</div></div>\n\n</td></tr>\n\n<tr><td><label>StartDt</label>:</td><td><input id=\"ProjectGiver_StartDt_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" value=\"\"/>\n<script>$j('#ProjectGiver_StartDt_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').date_input();</script>\n</td></tr>\n\n<tr><td><label>KrMon</label>:</td><td><input id=\"ProjectGiver_KrMon_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"\"/></td></tr>\n\n<tr><td><label>ProjectId</label>:</td><td>\n<input type=\"text\" id=\"ProjectGiver_ProjectId_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" value=\"0\" OnChange=\"\"/>\n<a style=\"cursor:pointer;\" onclick=\"\nif($j('#ProjectGiver_ProjectId_NewPopUp");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("_area').css('display')=='none') {\n$j('#ProjectGiver_ProjectId_NewPopUp");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("_area').show();\nApp3.Navigate2('local/Pages/ProjectSelect',{target:'ProjectGiver_ProjectId_NewPopUp");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("'});\n} else {\n$j('#ProjectGiver_ProjectId_NewPopUp");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("_area').hide();\n}\n\"><span class=\"EditLink\" style=\"display:none;\" id=\"ProjectGiver_ProjectId_NewPopUp");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("_display\">undefined</span>\n\n<button>Välj</button></a>\n<br/>\n<div id=\"ProjectGiver_ProjectId_NewPopUp");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("_area\" style=\"display:none;position:relative;\" datadisplay=\"ProjectGiver_ProjectId_NewPopUp");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("_display\" datastoreid=\"ProjectGiver_ProjectId_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\"><div id=\"ProjectGiver_ProjectId_NewPopUp");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" class=\"PopupSelect\" style=\"position:absolute;background:#EEEEEE;\">loading...</div></div>\n\n</td></tr>\n\n<tr><td><label>LastPayment</label>:</td><td><input id=\"ProjectGiver_LastPayment_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\" value=\"\"/>\n<script>$j('#ProjectGiver_LastPayment_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').date_input();</script>\n</td></tr>\n\n<tr><td><label>LastPaymentTot</label>:</td><td><input id=\"ProjectGiver_LastPaymentTot_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"\"/></td></tr>\n\n<tr><td><label>PaidTot</label>:</td><td><input id=\"ProjectGiver_PaidTot_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"\"/></td></tr>\n\n<tr><td><label>OneTimePromise</label>:</td><td><input id=\"ProjectGiver_OneTimePromise_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"\"/></td></tr>\n\n<tr><td><label>LastYearSi</label>:</td><td><input id=\"ProjectGiver_LastYearSi_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"\"/></td></tr>\n\n<tr><td><label>Status</label>:</td><td><input id=\"ProjectGiver_Status_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"\"/></td></tr>\n\n<tr><td><label>Db</label>:</td><td><input id=\"ProjectGiver_Db_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("\" type=\"text\"  value=\"\"/></td></tr>\n\n</tbody>\n<tfoot><tr><td colspan=\"2\"><center Task=\"Project4.Task\" Component=\"ProjectGiverNew_fields\" class=\"TaskEdit4\">\n\n<input type=\"button\" value=\"L&auml;gg till\" onclick=\"\ndataViews.ProjectGivers.newRecord({\nNewRecord:{\nGiverId:document.getElementById('ProjectGiver_GiverId_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value\n,\nStartDt:document.getElementById('ProjectGiver_StartDt_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value\n,\nKrMon:document.getElementById('ProjectGiver_KrMon_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value\n,\nProjectId:document.getElementById('ProjectGiver_ProjectId_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value\n,\nLastPayment:document.getElementById('ProjectGiver_LastPayment_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value\n,\nLastPaymentTot:document.getElementById('ProjectGiver_LastPaymentTot_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value\n,\nPaidTot:document.getElementById('ProjectGiver_PaidTot_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value\n,\nOneTimePromise:document.getElementById('ProjectGiver_OneTimePromise_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value\n,\nLastYearSi:document.getElementById('ProjectGiver_LastYearSi_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value\n,\nStatus:document.getElementById('ProjectGiver_Status_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value\n,\nDb:document.getElementById('ProjectGiver_Db_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value\n\n}\n,OnComplete:function(response){\n\n//document.getElementById('NewProjectGiver_Name");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').value = '';\n//document.getElementById('NewProjectGiver_Name");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').focus();\ndataViews.ProjectGivers.dataChanged();\nApp3.Navigate2('local/Pages/ProjectGivers',{target:'");
try{d=ns.target;}catch(e){d=''}out.push(d);
 out.push("',forceRead:true });\n\n}\n});\n\"/></center>\n</td></tr></tfoot>\n</table>\n<script>\ntry {\ndocument.getElementById('ProjectGiver_GiverId_New");
try{d=ns._ViewId;}catch(e){d=''}out.push(d);
 out.push("').focus();\n} catch(e) {\n//no problem.\n}\n</script>\n\n");

	return out.join('');
	}catch(e){
		console.error(e);
		return 'Template Error:'+e.message;
	}
}
